name: Build Node

on:
  push:
    branches: [master]
    paths:
      - 'workspace-node/**'
      - 'docker-compose.yml'
  pull_request:
    branches: [master]
    paths:
      - 'workspace-node/**'
      - 'docker-compose.yml'

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build-node:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node_version: [ "16", "17", "18" ]
        architecture: [ "linux/amd64", "linux/arm64" ]
        service: [ workspace-node ]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - name: Build the Docker image
        env:
          WORKSPACE_NODE_VERSION: ${{ matrix.node_version }}
          DOCKER_DEFAULT_PLATFORM: ${{ matrix.architecture }}
        run: |
          set -eux
          cp .env.example .env
          sed -i -- 's/=false/=true/g' .env
          sed -i -- 's/CHANGE_SOURCE=true/CHANGE_SOURCE=false/g' .env
          docker compose build ${{ matrix.service }}
          docker compose up -d --no-deps -- ${{ matrix.service }}
          docker compose exec -T -- ${{ matrix.service }} node -v
          docker compose down
      - name: List Images
        run: docker image inspect --format "{{.ID}} {{.RepoTags}} {{.Architecture}}" $(docker image ls -q)
