name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build-php:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php_version: [ "7.4", "8.0", "8.1", "8.2" ]
        architecture: [ "amd64", "arm64" ]
        service: [ php-fpm, php-worker, workspace, laravel-horizon ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU for ARM emulation
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build the Docker image
        env:
          PHP_VERSION: ${{ matrix.php_version }}
        run: |
          set -eux
          cp .env.example .env
          sed -i -- 's/=false/=true/g' .env
          sed -i -- 's/CHANGE_SOURCE=true/CHANGE_SOURCE=false/g' .env
          sed -i -- 's/PHPDBG=true/PHPDBG=false/g' .env
          sed -i -- 's/CASSANDRA=true/CASSANDRA=false/g' .env
          sed -i -- 's/GEARMAN=true/GEARMAN=false/g' .env
          sed -i -- 's/AEROSPIKE=true/AEROSPIKE=false/g' .env
          sed -i -- 's/PHALCON=true/PHALCON=false/g' .env
          sed -i -- 's/RDKAFKA=true/RDKAFKA=false/g' .env
          sed -i -- 's/MAILPARSE=true/MAILPARSE=false/g' .env
          sed -i -- 's/OCI8=true/OCI8=false/g' .env
          sed -i -- 's/V8JS=true/V8JS=false/g' .env
          sed -i -- 's/AUDIOWAVEFORM=true/AUDIOWAVEFORM=false/g' .env
          sed -i -- 's/SSDB=true/SSDB=false/g' .env
          sed -i -- 's/ENCHANT=true/ENCHANT=false/g' .env
          sed -i -- 's/MSSQL=true/MSSQL=false/g' .env
          
          # Build for the specified architecture
          docker compose build --platform linux/${{ matrix.architecture }} ${{ matrix.service }}

          # Run tests for the specified architecture
          docker compose up -d --no-deps --platform linux/${{ matrix.architecture }} ${{ matrix.service }}
          docker compose exec -T --platform linux/${{ matrix.architecture }} -- ${{ matrix.service }} php -m
          docker compose down

  build-other:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        architecture: [ "amd64", "arm64" ]
        service: [ 'adminer', 'apache2', 'mailcatcher', 'mailhog', 'mysql', 'nginx', 'phpmyadmin', 'postgres', 'redis', 'redis-webui', 'seleniarm', 'selenium' ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU for ARM emulation
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build the Docker image
        run: |
          cp .env.example .env
          sed -i -- 's/=false/=true/g' .env
          sed -i -- 's/CHANGE_SOURCE=true/CHANGE_SOURCE=false/g' .env
          
          # Build for the specified architecture
          docker compose build --platform linux/${{ matrix.architecture }} ${{ matrix.service }}
